# Generated by Django 2.2.10 on 2021-12-30 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='questionanswerchoice',
            options={'verbose_name': 'Вариант ответов для вопроса', 'verbose_name_plural': 'Варианты ответов для вопроса'},
        ),
        migrations.AddField(
            model_name='questionanswerchoice',
            name='is_correct_answer',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ ?'),
        ),
        migrations.CreateModel(
            name='UsersAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name='ID пользователя')),
                ('text_answer', models.TextField(verbose_name='Текстовый ответ')),
                ('choice_answers', models.ManyToManyField(blank=True, null=True, related_name='choosed_users', to='survey.QuestionAnswerChoice', verbose_name='Выборочный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_users', to='survey.Question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
    ]
